version: '3'
services:

  redis:
    image: 'redis:5.0-alpine'
    ports:
      - "6379:6379"

  slow_app:
    build:
      context: .
      dockerfile: proxy/slow_appDockerfile
    volumes:
      - ./:/usr/src/app
    env_file:
      - compose.env
    ports:
      - "8080:8080"

  task_producer:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: python /usr/src/app/benchmarks/task_producer.py
    env_file:
      - compose.env
    depends_on:
      - redis

  workers:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: wiji-cli --app benchmarks.wiji_app.myApp
    env_file:
      - compose.env
    depends_on:
      - redis
      - slow_app

  metrics:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
      - ./tmp/metrics:/tmp/metrics
    command: python /usr/src/app/benchmarks/metrics.py
    env_file:
      - compose.env
    depends_on:
      - redis
