version: '3'
services:
  redis:
    image: 'redis:3.0-alpine'
    ports:
      - "6379:6379"

  task_producer:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: python /usr/src/app/benchmarks/task_producer.py
    environment:
      aws_region_name: aws_region_name
      aws_access_key_id: aws_access_key_id
      aws_secret_access_key: aws_secret_access_key
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IN_DOCKER: yep
      USE_SQS: NO

  workers:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: wiji-cli --config benchmarks.wiji_app.myConf
    environment:
      aws_region_name: aws_region_name
      aws_access_key_id: aws_access_key_id
      aws_secret_access_key: aws_secret_access_key
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IN_DOCKER: yep
      USE_SQS: NO

  metrics:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    command: python /usr/src/app/benchmarks/metrics.py
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IN_DOCKER: yep
      USE_SQS: NO
